version: "3.8"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU12-ubuntu
    ports:
      - 1433:1433
    restart: unless-stopped
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      SA_PASSWORD: "Password1"
      PID: "Developer"
      ACCEPT_EULA: "Y"
  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: mssql
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.34.0
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## main Microsoft SQL database
      MSSQL_DATABASE_URL: Driver={ODBC Driver 17 for SQL Server};Server=tcp:mssql,1433;Database=maindb;Uid=sa;Pwd=Password1;
      ## disable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## disable telemetry
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myhasurasecret

volumes:
  mssql_data:
  pg_data:
